version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: arcade
      POSTGRES_USER: ferfox
      POSTGRES_PASSWORD: adminferfox
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

  backend:
    build: ./backend/
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: postgresql://ferfox:adminferfox@postgres:5432/arcade
      NODE_ENV: development
      PORT: 5000
      APP_JWT_SECRET: tintinsefuealaguerra
      INIT_ADMIN: admin@arcade.com
    volumes: 
      - ./backend:/app
    ports: 
      - 5000:5000
    command: "npm run dev"
    depends_on:
      - postgres
    networks:
      - postgres

  frontend:
    build: ./frontend/
    container_name: frontend
    restart: always
    volumes: 
      - ./frontend:/app
    ports: 
      - 5173:5173
    environment:
      BASE_URL: "http://localhost:5173"
    command: "npm run dev"
    depends_on:
      - backend

networks:
  postgres:
    driver: bridge

volumes:
    postgres: