version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ferfox
      POSTGRES_PASSWORD: adminferfox
      PGDATA: /data_tmp
    volumes:
      - ./.data_tmp:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
    postgres: